name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: MrPkMehta
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Upload snake SVG to repository
        run: |
          mkdir -p output
          cp dist/github-contribution-grid-snake.svg output/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
